=== fugerit-org/fj-doc/fj-doc-freemarker/src/main/resources/config_fm_xsd/freemarker-doc-process-1-0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

	/*
	 * @(#)freemarker-doc-process-1-0.xsd 
	 *
	 * @project    : fj-doc-freemarker
	 * @creation   : 2023-07-12
	 * @version    : 1.0.0-rc.7 (2026-06-25)
	 *
	 * XSD for Freemarker Doc Process Configuration
	 */

	Sample doc : 	
	
<doc
	xmlns="https://freemarkerdocprocess.fugerit.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://freemarkerdocprocess.fugerit.org https://www.fugerit.org/data/java/doc/xsd/freemarker-doc-process-1-0.xsd" > 	
</doc>	
	
-->
<xsd:schema xmlns='http://www.w3.org/2000/10/XMLSchema'
	targetNamespace='https://freemarkerdocprocess.fugerit.org'
	xmlns:fdp='https://freemarkerdocprocess.fugerit.org' xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name='freemarker-doc-process-config'>
		<xsd:annotation>
			<xsd:documentation>This is the root element of freemarker-doc-process configuration file</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref='fdp:docHandlerConfig' minOccurs="0" maxOccurs="1" />
				<xsd:element ref='fdp:docChain' minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="validating" type="xsd:boolean" use="optional" default="false">
				<xsd:annotation>
					<xsd:documentation>If set to 'true' the FreemarkerDocProcessConfig will try to validate the source. (since 8.9.1)</xsd:documentation>
					<xsd:documentation>NOTE: if active, source reader will be buffered, potentially resulting in higher memory usage.</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="failOnValidate" type="xsd:boolean" use="optional" default="false">
				<xsd:annotation>
					<xsd:documentation>If set to 'true' the FreemarkerDocProcessConfig will fail in case of validation errors, if 'false' will just print the result as warning. (since 8.9.1)</xsd:documentation>
					<xsd:documentation>NOTE: 'validating' is set to true, this attribute is ignored.</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="cleanSource" type="xsd:boolean" use="optional" default="false">
				<xsd:annotation>
					<xsd:documentation>If set to 'true' the FreemarkerDocProcessConfig will try to clean the source (i.e. DocXmlUtils.cleanXml()). (since 8.9.1)</xsd:documentation>
					<xsd:documentation>NOTE: if active, source reader will be buffered, potentially resulting in higher memory usage.</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="table-check-integrity" type="fdp:tableIntegrityCheckType" use="optional" default="disabled">
				<xsd:annotation>
					<xsd:documentation>Global default for 'table-check-integrity', it will check the integrity of a table, correct number of columns per row. (since 8.15.0)</xsd:documentation>
					<xsd:documentation>Allowed values : 'disabled' (default value), 'warn', 'fail'.</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name='docHandlerConfig' type="fdp:docHandlerConfigType">
		<xsd:annotation>
			<xsd:documentation>Configuration for DocHandlerFacade containing all needed DocTypeHandlers</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	
	<xsd:complexType name="docHandlerConfigType">
		<xsd:sequence>
			<xsd:element ref="fdp:docHandler" minOccurs="0" maxOccurs="unbounded"></xsd:element>
		</xsd:sequence>
		<xsd:attribute name="registerById" type="xsd:boolean" use="optional" default="false">
			<xsd:annotation>
				<xsd:documentation>If set to true, the handlers will be registered by id</xsd:documentation>
			</xsd:annotation>				
		</xsd:attribute>	
		<xsd:attribute name="allowDuplicatedId" type="xsd:boolean" use="optional" default="false">
			<xsd:annotation>
				<xsd:documentation>If set to true, duplicated id will be allowed (the last one will overwrite the others)</xsd:documentation>
			</xsd:annotation>				
		</xsd:attribute>		
	</xsd:complexType>	
	
	<xsd:element name='docHandler' type="fdp:docHandlerType">
		<xsd:annotation>
			<xsd:documentation>Configuration of a specific DocTypeHandler as FactoryType</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	
	<xsd:complexType name="docHandlerType">
		<xsd:sequence>
			<xsd:element ref="fdp:docHandlerCustomConfig" minOccurs="0" maxOccurs="1">
			</xsd:element>			
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>Id of the handler</xsd:documentation>
			</xsd:annotation>				
		</xsd:attribute>
		<xsd:attribute name="info" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>Type of the handler</xsd:documentation>
			</xsd:annotation>				
		</xsd:attribute>				
		<xsd:attribute name="type" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>Type of the handler (fully qualified class name implementing DocTypeHandler)</xsd:documentation>
			</xsd:annotation>				
		</xsd:attribute>
		<xsd:attribute name="unsafe" type="xsd:boolean" use="optional" default="false">
			<xsd:annotation>
				<xsd:documentation>'true' is the handler is too be considered unsafe </xsd:documentation>
			</xsd:annotation>				
		</xsd:attribute>
		<xsd:attribute name="unsafeMode" type="xsd:string" use="optional" default="log-message">
			<xsd:annotation>
				<xsd:documentation>Unsafe handling message, ( 'log-message' for simple message or 'log-trace' for full trace) </xsd:documentation>
			</xsd:annotation>				
		</xsd:attribute>																						
	</xsd:complexType>				
					
	<xsd:element name='docHandlerCustomConfig' type="fdp:docHandlerCustomConfigType">
		<xsd:annotation>
			<xsd:documentation>Custom configuration of a doc handler, it can contains unchecked attributes and child elements.</xsd:documentation>
		</xsd:annotation>
	</xsd:element>					
					
	<xsd:complexType name="docHandlerCustomConfigType">	
		<xsd:sequence>
      		<xsd:any minOccurs="0" processContents="skip"/>
    	</xsd:sequence>			
		<xsd:anyAttribute processContents="skip"/>
	</xsd:complexType>		
	
	<xsd:element name='docChain' type="fdp:docChainType">
		<xsd:annotation>
			<xsd:documentation>A document processing chain</xsd:documentation>
		</xsd:annotation>
	</xsd:element>

	<xsd:complexType name="docChainType">
		<xsd:sequence>
			<xsd:element ref="fdp:chainStep" minOccurs="0" maxOccurs="unbounded"></xsd:element>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>A chain ID</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="parent" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>A chain parent (will inherits all the chainStep)</xsd:documentation>
			</xsd:annotation>		
		</xsd:attribute>
		<xsd:attribute name="sourceType" type="fdp:sourceType" use="optional" default="xml">
			<xsd:annotation>
				<xsd:documentation>The source type : xml (default), json, yaml or kotlin. (since 8.9.6)</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>	

	<xsd:element name='chainStep' type="fdp:chainStepType">
		<xsd:annotation>
			<xsd:documentation>A step in a docChain</xsd:documentation>
		</xsd:annotation>
	</xsd:element>

	<xsd:complexType name="chainStepType">
		<xsd:choice>
			<xsd:element ref="fdp:config" minOccurs="1" maxOccurs="1"></xsd:element>
			<xsd:element ref="fdp:function" minOccurs="0" maxOccurs="unbounded"></xsd:element>
			<xsd:element ref="fdp:map" minOccurs="0" maxOccurs="unbounded"></xsd:element>
		</xsd:choice>
		<xsd:attribute name="stepType" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>Can be a java type value implementing DocProcessorBasic or a fixed value for 'config', 'map', 'function', 'complex',</xsd:documentation>
				<xsd:documentation>'skipfm' (skip FreeMarkerProcessing, since 8.9.7)</xsd:documentation>
				<xsd:documentation>'kotlin' (skip FreeMarkerProcessing, since 8.10.0, use kotlin script, kts-path must be set, dataModel map can still be used and will be bound to the script)</xsd:documentation>
			</xsd:annotation>		
		</xsd:attribute>
		<xsd:attribute name="map-atts" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>Comma separated list of attributes to map or use 'map-all' attribute to map all attributes</xsd:documentation>
			</xsd:annotation>		
		</xsd:attribute>
		<xsd:attribute name="map-all" type="xsd:boolean" use="optional">
			<xsd:annotation>
				<xsd:documentation>'true' if all attributes must be mapped. default 'false'. (if set to 'true' has precedence over map-atts)</xsd:documentation>
			</xsd:annotation>		
		</xsd:attribute>
		<xsd:attribute name="template-path" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>Free marker template path (relative to template base path provided in 'config' step).</xsd:documentation>
			</xsd:annotation>		
		</xsd:attribute>
		<xsd:attribute name="kts-path" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>Kotlin script (KTS) path in classpath (FreeMarker template base is ignored).</xsd:documentation>
				<xsd:documentation>(in 'kotlin' step it is possible to use 'template-path' as an alias for this attribute).</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>	

	<xsd:element name='config' type="fdp:configType">
		<xsd:annotation>
			<xsd:documentation>Will creates a new free marker configuration</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	
	<xsd:element name='function' type="fdp:propertyType">
		<xsd:annotation>
			<xsd:documentation>The data of a freemarker function to map (the 'name' attributes will be the key, and a new instance of the 'value' attribute as value)</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	
	<xsd:element name='map' type="fdp:propertyType">
		<xsd:annotation>
			<xsd:documentation>An object will be mapped from DocProcessContext to Freemarker Map (the 'name' attributes will be the key, and the 'value' will be used to search in the DocProcessContext attributes)</xsd:documentation>
		</xsd:annotation>
	</xsd:element>		

	<xsd:complexType name="configType">
		<xsd:attribute name="id" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>The new freemarker configuration ID</xsd:documentation>
			</xsd:annotation>			
		</xsd:attribute>
		<xsd:attribute name="path" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>base freemarker template path</xsd:documentation>
			</xsd:annotation>				
		</xsd:attribute>
		<xsd:attribute name="version" type="xsd:string" use="optional" default="2.3.31">
			<xsd:annotation>
				<xsd:documentation>freemarker version to use</xsd:documentation>
			</xsd:annotation>						
		</xsd:attribute>
		<xsd:attribute name="mode" type="xsd:string" use="optional" default="class">
			<xsd:annotation>
				<xsd:documentation>The class loading mode</xsd:documentation>
			</xsd:annotation>								
		</xsd:attribute>
		<xsd:attribute name="class" type="xsd:string" use="optional" default="org.fugerit.java.doc.freemarker.process.FreemarkerDocProcessConfig">
			<xsd:annotation>
				<xsd:documentation>This class's classloader will be used</xsd:documentation>
			</xsd:annotation>									
		</xsd:attribute>
		<xsd:attribute name="exception-handler" type="xsd:string" use="optional" default="RETHROW_HANDLER">
			<xsd:annotation>
				<xsd:documentation>Just a referenced to the relevant freemarker configuration</xsd:documentation>
			</xsd:annotation>		
		</xsd:attribute>
		<xsd:attribute name="log-exception" type="xsd:boolean" use="optional" default="false">
			<xsd:annotation>
				<xsd:documentation>Just a referenced to the relevant freemarker configuration</xsd:documentation>
			</xsd:annotation>				
		</xsd:attribute>
		<xsd:attribute name="wrap-unchecked-exceptions" type="xsd:boolean" use="optional" default="true">
			<xsd:annotation>
				<xsd:documentation>Just a referenced to the relevant freemarker configuration</xsd:documentation>
			</xsd:annotation>				
		</xsd:attribute>
		<xsd:attribute name="fallback-on-null-loop-variable" type="xsd:boolean" use="optional" default="false">
			<xsd:annotation>
				<xsd:documentation>Just a referenced to the relevant freemarker configuration</xsd:documentation>
			</xsd:annotation>				
		</xsd:attribute>
		<xsd:attribute name="load-bundled-functions" type="xsd:boolean" use="optional" default="false">
			<xsd:annotation>
				<xsd:documentation>It will load all the default funs with the default name</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>	
	
	<xsd:complexType name="propertyType">
		<xsd:attribute name="name" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>Name map attribute</xsd:documentation>
			</xsd:annotation>				
		</xsd:attribute>
		<xsd:attribute name="value" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>Value map attribute</xsd:documentation>
			</xsd:annotation>						
		</xsd:attribute>
	</xsd:complexType>

	<xsd:simpleType name="sourceType">
		<xsd:annotation>
			<xsd:documentation>The source type</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="xml"/>
			<xsd:enumeration value="json"/>
			<xsd:enumeration value="yaml"/>
			<xsd:enumeration value="kotlin"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="tableIntegrityCheckType">
		<xsd:annotation>
			<xsd:documentation>The source type</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="disabled"/>
			<xsd:enumeration value="warn"/>
			<xsd:enumeration value="fail"/>
		</xsd:restriction>
	</xsd:simpleType>

</xsd:schema>

=== fugerit-org/fj-doc/fj-doc-native-quarkus/src/main/resources/fj-doc-native-quarkus/fm-doc-process-config.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- generated from template 'fm-doc-process-config-template.ftl' on 2024-11-01T20:36:51.311Z -->
<freemarker-doc-process-config
        xmlns="https://freemarkerdocprocess.fugerit.org"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://freemarkerdocprocess.fugerit.org https://www.fugerit.org/data/java/doc/xsd/freemarker-doc-process-1-0.xsd" >

    <!--
    Documentation :
    https://venusdocs.fugerit.org/guide/

    Configuration reference :
    https://venusdocs.fugerit.org/fj-doc-freemarker/src/main/docs/fdp_xsd_config_ref.html
    -->

    <docHandlerConfig registerById="true">
        <!-- Type handler for markdown format -->
        <docHandler id="md-ext" info="md" type="org.fugerit.java.doc.base.typehandler.markdown.SimpleMarkdownExtTypeHandler" />
        <!-- Type henalder for xml format, generates the source xml:doc -->
        <docHandler id="xml-doc" info="xml" type="org.fugerit.java.doc.base.config.DocTypeHandlerXMLUTF8" />
        <!-- Type handler for html using freemarker -->
        <docHandler id="html-fm" info="html" type="org.fugerit.java.doc.freemarker.html.FreeMarkerHtmlTypeHandlerEscapeUTF8" />
        <!-- Type handler for html using freemarker (fragment version, only generates body content no html or head part -->
        <docHandler id="html-fragment-fm" info="fhtml" type="org.fugerit.java.doc.freemarker.html.FreeMarkerHtmlFragmentTypeHandlerEscapeUTF8" />
        <!-- type handler for asciidoc using freemarker -->
        <docHandler id="asciidoc-fm" info="adoc" type="org.fugerit.java.doc.freemarker.asciidoc.FreeMarkerAsciidocTypeHandlerUTF8" />
        <!-- type handler for csv using opencsv -->
        <docHandler id="csv" info="csv" type="org.fugerit.java.doc.mod.opencsv.OpenCSVTypeHandlerUTF8" />
    </docHandlerConfig>

    <docChain id="shared">
        <chainStep stepType="config">
            <config
                    id="fj_doc_config_fm_fjdocnativequarkus"
                    class="org.fugerit.java.fjdocnativequarkus.DocHelper"
                    exception-handler="RETHROW_HANDLER"
                    fallback-on-null-loop-variable="false"
                    log-exception="false"
                    mode="class"
                    path="/fj-doc-native-quarkus/template/"
                    version="2.3.32"
                    wrap-unchecked-exceptions="true"
                    load-bundled-functions="true"
            />
        </chainStep>
    </docChain>

    <!-- example document chain xml -->
    <docChain id="document" parent="shared">
        <chainStep stepType="complex" map-all="true" template-path="${chainId}.ftl"/>
    </docChain>




</freemarker-doc-process-config>

=== fugerit-org/fj-doc/fj-doc-freemarker/src/test/resources/fj_doc_test/freemarker-doc-process_alt.xml
<?xml version="1.0" encoding="utf-8"?>
<freemarker-doc-process-config
	xmlns="https://freemarkerdocprocess.fugerit.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://freemarkerdocprocess.fugerit.org https://www.fugerit.org/data/java/doc/xsd/freemarker-doc-process-1-0.xsd" > 	

	<docHandlerConfig>
		<!-- Type handler for markdown format -->
		<docHandler id="md-ext" info="md" type="org.fugerit.java.doc.base.typehandler.markdown.SimpleMarkdownExtTypeHandler" />
		<!-- Type henalder for xml format, generates the source xml:doc -->
		<docHandler id="xml-doc" info="xml" type="org.fugerit.java.doc.base.config.DocTypeHandlerXMLUTF8" />
	</docHandlerConfig>

	<docChain id="shared">
		<chainStep stepType="config">
			<config id="FJ_DOC_TEST"
				version="2.3.32"
				path="/fj_doc_test/template/"
				exception-handler="IGNORE_HANDLER"
				log-exception="false"
				wrap-unchecked-exceptions="true"
				fallback-on-null-loop-variable="false"/>
		</chainStep>
		<chainStep stepType="function">
			<function name="imageBase64CLFun" value="org.fugerit.java.doc.freemarker.fun.ImageBase64CLFun"/>
			<function name="messageFormat" value="org.fugerit.java.doc.freemarker.fun.SimpleMessageFun"/>
			<function name="sumLong" value="org.fugerit.java.doc.freemarker.fun.SimpleSumLongFun"/>
		</chainStep>
	</docChain>

	<docChain id="sample_chain" parent="shared">
		<chainStep stepType="complex" template-path="${chainId}.ftl"/>
	</docChain>
	
	<docChain id="test_01" parent="shared">
		<chainStep stepType="complex" template-path="${chainId}.ftl" map-atts="test"/>
	</docChain>
	
	<docChain id="test_01_alt" parent="shared">
		<chainStep stepType="complex" template-path="test_01.ftl" map-all="true"/>
	</docChain>
	
	<docChain id="test_01_fail" parent="shared">
		<chainStep stepType="complex" map-all="true"/>
	</docChain>

	<docChain id="test_01_inline" parent="shared" templatePath="test_01.ftl" mapAtts="all" />

</freemarker-doc-process-config>

=== fugerit-org/fj-doc/fj-doc-mod-fop/src/main/resources/fj_doc_mod_fop_config/fm-fop-process-config.xml
<?xml version="1.0" encoding="utf-8"?>
<freemarker-doc-process-config
	xmlns="https://freemarkerdocprocess.fugerit.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://freemarkerdocprocess.fugerit.org https://www.fugerit.org/data/java/doc/xsd/freemarker-doc-process-1-0.xsd" > 	

	<!--
		Configuration stub version : 003 (2023-07-19)
	-->

	

	<docChain id="fop-freemarker">
		<chainStep stepType="config">
			<config
				id="FJDOC_MOD_FOP_FREEMARKER_CONFIG"
				class="org.fugerit.java.doc.mod.fop.FopConfigDefault"
				exception-handler="RETHROW_HANDLER"
				fallback-on-null-loop-variable="false"
				log-exception="false"
				mode="class"
				path="/fj_doc_mod_fop_config/template/"
				version="2.3.29"
				wrap-unchecked-exceptions="true"
			/>
		</chainStep>
		<chainStep stepType="function">
			<function name="base64ToString" value="org.fugerit.java.doc.freemarker.fun.Base64ToStringFun"/>
            <function name="stringToBase64" value="org.fugerit.java.doc.freemarker.fun.StringToBase64Fun"/>
		</chainStep>
		<chainStep stepType="map">
			<map name="docBase" value="docBase"/>
			<map name="docType" value="docType"/>
		</chainStep>
		<chainStep stepType="complex" template-path="fop_doc.ftl">
		</chainStep>
	</docChain>

		
</freemarker-doc-process-config>

=== fugerit-org/fj-doc/fj-doc-lib-autodoc/src/main/resources/fj_doc_lib_autodoc/fm-doc-process-config-autodoc.xml
<?xml version="1.0" encoding="utf-8"?>
<freemarker-doc-process-config
	xmlns="https://freemarkerdocprocess.fugerit.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://freemarkerdocprocess.fugerit.org https://www.fugerit.org/data/java/doc/xsd/freemarker-doc-process-1-0.xsd" > 	

	<!--
		Configuration stub version : 003 (2023-07-19)
	-->

	<docChain id="shared">
		<chainStep stepType="config">
			<config
				id="FJ_DOC_LIB_AUTODOC"
				class="org.fugerit.java.doc.lib.autodoc.AutodocModule"
				exception-handler="RETHROW_HANDLER"
				fallback-on-null-loop-variable="false"
				log-exception="false"
				mode="class"
				path="/fj_doc_lib_autodoc/template/"
				version="2.3.29"
				wrap-unchecked-exceptions="true"
			/>
		</chainStep>
		<chainStep stepType="function">
			<function name="annotationAsSingleStringFun" value="org.fugerit.java.doc.lib.autodoc.fun.AnnotationAsSingleStringFun"/>
			<function name="messageFormat" value="org.fugerit.java.doc.freemarker.fun.SimpleMessageFun"/>
		</chainStep>
	</docChain>

	<docChain id="autodoc" parent="shared">
		<chainStep stepType="complex" map-atts="autodocModel" template-path="${chainId}.ftl"/>
	</docChain>

	<docChain id="autodoc_schema" parent="shared">
		<chainStep stepType="complex" map-all="true" template-path="${chainId}.ftl"/>
	</docChain>

	<docChain id="autodoc_detail" parent="shared">
		<chainStep stepType="complex" map-atts="autodocDetailModel" template-path="${chainId}.ftl"/>
	</docChain>

	<docChain id="autodoc_meta" parent="shared">
		<chainStep stepType="complex" map-atts="autodocMetaModel" template-path="${chainId}.ftl"/>
	</docChain>
		
</freemarker-doc-process-config>

=== fugerit-org/fj-doc/fj-doc-freemarker/src/main/resources/fj_doc_freemarker_config/fm-freemarker-doc-process-config.xml
<?xml version="1.0" encoding="utf-8"?>
<freemarker-doc-process-config
	xmlns="https://freemarkerdocprocess.fugerit.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://freemarkerdocprocess.fugerit.org https://www.fugerit.org/data/java/doc/xsd/freemarker-doc-process-1-0.xsd" >

	<docHandlerConfig registerById="true">

		<!-- Type handler for markdown format -->
		<docHandler id="md-ext" info="md" type="org.fugerit.java.doc.base.typehandler.markdown.SimpleMarkdownExtTypeHandler" />
		<!-- Type henalder for xml format, generates the source xml:doc -->
		<docHandler id="xml-doc" info="xml" type="org.fugerit.java.doc.base.config.DocTypeHandlerXMLUTF8" />

		<!-- Type handlers for html using freemarker -->
		<docHandler id="html-fm" info="html" type="org.fugerit.java.doc.freemarker.html.FreeMarkerHtmlTypeHandlerEscapeUTF8" />
		<!-- Type handlers for html using freemarker (fragment version, only generates body content no html or head part -->
		<docHandler id="html-fragment-fm" info="fhtml" type="org.fugerit.java.doc.freemarker.html.FreeMarkerHtmlFragmentTypeHandlerEscapeUTF8" />

		<!-- Type handlers for asciidoc using freemarker -->
		<docHandler id="asoc-fm" info="asoc" type="org.fugerit.java.doc.freemarker.asciidoc.FreeMarkerAsciidocTypeHandlerUTF8" />

		<!-- Simple default PDF FOP Type handler with no added configuration   -->
		<docHandler id="pdf-fop" info="pdf" type="org.fugerit.java.doc.mod.fop.PdfFopTypeHandler" unsafe="true" unsafeMode="log-message"/>

		<!-- XLSX type hanlder  -->
		<docHandler id="xlsx-poi" info="xlsx" type="org.fugerit.java.doc.mod.poi.XlsxPoiTypeHandler" unsafe="true" unsafeMode="log-message"/>

		<!-- CSV type hanlder  -->
		<docHandler id="csv-opencsv" info="csv" type="org.fugerit.java.doc.mod.opencsv.OpenCSVTypeHandler" unsafe="true" unsafeMode="log-message"/>

	</docHandlerConfig>

	<docChain id="base-freemarker">
		<chainStep stepType="config">
			<config id="FJDOC_MOD_FREEMARKER_HTML_CONFIG" 
				version="2.3.29"
				path="/fj_doc_freemarker_config/template/"
				mode="class" 
				class="org.fugerit.java.doc.freemarker.process.DocChainModel"
				exception-handler="RETHROW_HANDLER"
				log-exception="false"
				wrap-unchecked-exceptions="true"
				fallback-on-null-loop-variable="false"/>
		</chainStep>
	</docChain>

	<docChain id="base-freemarker-html" parent="base-freemarker">
		<chainStep stepType="map">
			<map name="docBase" value="docBase"/>
			<map name="docType" value="docType"/>
			<map name="escapeTextAsHtml" value="escapeTextAsHtml"/>
		</chainStep>
	</docChain>

	<docChain id="html-freemarker" parent="base-freemarker-html">
		<chainStep stepType="complex" template-path="html_doc.ftl"/>
	</docChain>
		
	<docChain id="html-fragment-freemarker" parent="base-freemarker-html">
		<chainStep stepType="complex" template-path="html_fragment.ftl"/>
	</docChain>

	<docChain id="freemarker-doc-process-config-stub" parent="base-freemarker">
		<chainStep stepType="map">
			<map name="stubParams" value="stubParams"/>
			<map name="configModel" value="configModel"/>
		</chainStep>
		<chainStep stepType="complex" template-path="freemarker-doc-process-config-stub.ftl"/>
	</docChain>

	<docChain id="freemarker-verify-syntax-report" parent="base-freemarker">
		<chainStep stepType="complex" map-all="1" template-path="${chainId}.ftl"/>
	</docChain>

	<docChain id="asciidoc" parent="base-freemarker-html">
		<chainStep stepType="complex" template-path="asciidoc.ftl"/>
	</docChain>

</freemarker-doc-process-config>

=== fugerit-org/fj-doc/fj-doc-sample/src/main/resources/config/freemarker-doc-process-pdf-a-ua.xml
<?xml version="1.0" encoding="utf-8"?>
<freemarker-doc-process-config
	xmlns="https://freemarkerdocprocess.fugerit.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://freemarkerdocprocess.fugerit.org https://www.fugerit.org/data/java/doc/xsd/freemarker-doc-process-1-0.xsd" > 	

	<docHandlerConfig registerById="true" allowDuplicatedId="true">
		<docHandler id="pdf-a-ua-fop" info="pdf" type="org.fugerit.java.doc.mod.fop.PdfFopTypeHandler">
			<docHandlerCustomConfig charset="UTF-8"
									fop-config-mode="classloader"
									fop-config-classloader-path="fop-config-pdf-a-ua.xml"
									pdf-a-mode="PDF/A-1b"
									pdf-ua-mode="PDF/UA-1"/>
		</docHandler>
	</docHandlerConfig>

	<docChain id="shared">
		<chainStep stepType="config">
			<config id="FJ_SAMPLE_TEST_PDF_A_UA" version="2.3.33" path="/free_marker/"/>
		</chainStep>
		<chainStep stepType="function">
			<function name="messageFormat" value="org.fugerit.java.doc.freemarker.fun.SimpleMessageFun"/>
			<function name="sumLong" value="org.fugerit.java.doc.freemarker.fun.SimpleSumLongFun"/>
		</chainStep>
		<chainStep stepType="test.org.fugerit.java.doc.sample.freemarker.TestFreeMarker01DataStep"/>
		<chainStep stepType="map">
			<map name="list" value="userList"/>
			<map name="testBase64Img" value="testBase64Img"/>
		</chainStep>
	</docChain>

	<docChain id="pdf_a_test" parent="shared">
		<chainStep stepType="complex" template-path="pdf_a_test.ftl"/>
	</docChain>

</freemarker-doc-process-config>

=== fugerit-org/fj-doc/fj-doc-freemarker/src/test/resources/fj_doc_test/freemarker-doc-process-2.xml
<?xml version="1.0" encoding="utf-8"?>
<freemarker-doc-process-config
	xmlns="https://freemarkerdocprocess.fugerit.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://freemarkerdocprocess.fugerit.org https://www.fugerit.org/data/java/doc/xsd/freemarker-doc-process-1-0.xsd"
	validating="true"
	failOnValidate="true"
	cleanSource="false">

	<docHandlerConfig>
		<docHandler id="html-fm" info="html" type="org.fugerit.java.doc.freemarker.html.FreeMarkerHtmlTypeHandlerEscapeUTF8" />
	</docHandlerConfig>

	<docChain id="shared">
		<chainStep stepType="config">
			<config id="FJ_DOC_TEST"
				version="2.3.31"
				path="/fj_doc_test/template/"
				mode="class" 
				class="org.fugerit.java.doc.freemarker.fun.CleanXmlFun"
				exception-handler="RETHROW_HANDLER"
				log-exception="false"
				wrap-unchecked-exceptions="true"
				fallback-on-null-loop-variable="false"
				load-bundled-functions="true"/>
		</chainStep>
	</docChain>

	<docChain id="sample_chain" parent="shared">
		<chainStep stepType="complex" template-path="${chainId}.ftl"/>
	</docChain>

	<docChain id="error_chain" parent="shared">
		<chainStep stepType="complex" template-path="${chainId}.ftl"/>
	</docChain>

</freemarker-doc-process-config>
